name: tabby_flutter_inapp_sdk
description: Tabby Flutter SDK
version: 1.7.0
homepage: https://github.com/tabby-ai/tabby_flutter_inapp_sdk

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Remote API
  http: ^1.2.2

  # Webview
  flutter_inappwebview: ^6.1.0+1

  # UUID
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.21.1
flutter:
  assets:
    - assets/images/tabby-badge.png
    - assets/images/2.0x/tabby-badge.png
    - assets/images/3.0x/tabby-badge.png
    - assets/images/r1.png
    - assets/images/r2.png
    - assets/images/r3.png
    - assets/images/r4.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial-Regular.ttf
          weight: 500
